---

# Add proxy to /etc/environment
- name: Add proxy to /etc/environment
  become: yes
  lineinfile:
    line: "HTTP_PROXY=\"{{ proxy }}\"\nHTTPS_PROXY=\"{{ proxy }}\"\nhttp_proxy=\"{{ proxy }}\"\nhttps_proxy=\"{{ proxy }}\"\nno_proxy=\"localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au\"\n"
    dest: /etc/environment

- name: Reboot instance
  become: yes
  reboot:
    reboot_timeout: 1200

- name: Update apt
  tags: always
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
# apt-get upgrade; apt-get update

- name: Install dependencies
  tags: always
  become: yes
  apt:
    name: ['python3-pip','git','xfsprogs','apt-transport-https','build-essential','ca-certificates','curl','gnupg','lsb-release','python-setuptools','software-properties-common','nodejs','npm','node-grunt-cli','jq']
    # ['vim','unzip']
    state: latest
    update_cache: yes

- name: Add docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    update_cache: yes

- name: install docker
  become: yes
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io']
    state: latest
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    state: present

- name: Install python libraries
  become: yes
  pip:
    name: ['jinja2','tweepy','couchdb','urllib3']