---
# - name: deploy map-reduce functions for tweets-db
#   become: yes
#   shell: "curl -X POST -d '{\"_id\": \"_design/tweets\",\"views\": {\"tweetsPerPlace\": {\"map\": \"function (doc){emit(doc.Place, 1);}\",\"reduce\": \"_count\" }},\"language\": \"javascript\"}' http://\"{{ couchdb_user }}\":\"{{ couchdb_password }}\"@{{ groups['dbMaster'][0] }}:5984/tweets-db -H \"content-type:application/json\""

# - name: deploy map-reduce functions for aurin-db
#   become: yes
#   uri:
#     url: http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_aurin_db_name }}
#     status_code: 200
#     method: POST
#     user: "{{ couchdb_user }}"
#     password: "{{ couchdb_password }}"
#     body_format: json
#     body: "{\"_id\": \"_design/rates\",\"views\":
#       {\"employmentRateByState\": {\"map\": \"function (doc){emit(doc.state_name_2016, doc.mpy_rt_15_24);}\",\"reduce\": \"function (keys, values, rereduce){return sum(values)/values.length;}\"},
#       \"youthUnemploymentRateByState\": {\"map\": \"function (doc){emit(doc.state_name_2016, doc.yth_unemp_rt_15_24);}\",\"reduce\": \"function (keys, values, rereduce){return sum(values)/values.length;}\"}
#       },\"language\": \"javascript\"}"
#     headers:
#       Content-Type: "application/json"

- name: deploy map-reduce functions for tweets-db
  become: yes
  uri:
    url: http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_tweets_name }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"_id\": \"_design/tweets\",\
            \"views\": {\"tweetsPerPlace\": {\"map\": \"function (doc){emit(doc.Place, 1);}\",\"reduce\": \"_count\"},\
            \"nswTweetsFrom2020ByMonth\": {\"map\": \"function(doc) {let dateSegs = doc.Date.split(' ');const month = dateSegs[1];const year = dateSegs[dateSegs.length - 1];const monthMap = {'Jan': 1,'Feb': 2,'Mar': 3,'Apr': 4,'May': 5,'Jun': 6,'Jul': 7,'Aug': 8,'Sep': 9,'Oct': 10,'Nov': 11,'Dec': 12};const stateNames = ['nsw', 'new south wales'];const tweetPlaceSegs = doc.Place.split(',').map(i => i.trim().toLowerCase());let locationIndex = 0;if (tweetPlaceSegs.some((item) => {locationIndex = stateNames.indexOf(item);return locationIndex >= 0;})) {if (parseInt(year) >= 2020) {emit([parseInt(year), monthMap[month]], 1);}}}\",\"reduce\": \"_sum\"},\
            \"vicTweetsFrom2020ByMonth\": {\"map\": \"function(doc) {let dateSegs = doc.Date.split(' ');const month = dateSegs[1];const year = dateSegs[dateSegs.length - 1];const monthMap = {'Jan': 1,'Feb': 2,'Mar': 3,'Apr': 4,'May': 5,'Jun': 6,'Jul': 7,'Aug': 8,'Sep': 9,'Oct': 10,'Nov': 11,'Dec': 12};const stateNames = ['nsw', 'new south wales'];const tweetPlaceSegs = doc.Place.split(',').map(i => i.trim().toLowerCase());let locationIndex = 0;if (tweetPlaceSegs.some((item) => {locationIndex = stateNames.indexOf(item);return locationIndex >= 0;})) {if (parseInt(year) >= 2020) {emit([parseInt(year), monthMap[month]], 1);}}}\",\"reduce\": \"_sum\"}},\
            \"language\": \"javascript\"}"
    headers:
      Content-Type: "application/json"

- name: deploy map-reduce functions for labour-db
  become: yes
  uri:
    url: http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_aurin_labour }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"_id\": \"_design/unemployment\",\
            \"views\":{\"employmentRateByState\": {\"map\": \"function (doc){emit(doc.state_name_2016, doc.mpy_rt_15_64);}\",\"reduce\": \"function (keys, values, rereduce){return sum(values)/values.length;}\"},\
            \"youthUnemploymentRateByState\": {\"map\": \"function (doc){emit(doc.state_name_2016, doc.yth_unemp_rt_15_24);}\",\"reduce\": \"function (keys, values, rereduce){return sum(values)/values.length;}\"}},\
            \"language\": \"javascript\"}"
    headers:
      Content-Type: "application/json"

- name: deploy map-reduce functions for mortality-db
  become: yes
  uri:
    url: http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_aurin_mortality }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"_id\": \"_design/mortality\",\
            \"views\": {\"mortalityBySA4\": {\"map\": \"function (doc){emit(doc.sa4_name, [doc.p_crude_rt, doc.p_rt_ratio]);}\"}},\
            \"language\": \"javascript\"}"
    headers:
      Content-Type: "application/json"

- name: deploy map-reduce functions for crash-db
  become: yes
  uri:
    url: http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_aurin_crash }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"_id\": \"_design/crashes\",\
            \"views\":{\"nswByMonth\": {\"map\": \"function (doc) {if (doc.State.toLowerCase() === 'nsw') {emit([doc.Year, doc.Month], doc.Count);}}\"},\
            \"vicByMonth\": {\"map\": \"function (doc){if (doc.State.toLowerCase() === 'vic') {emit([doc.Year, doc.Month], doc.Count);}}\"}},\
            \"language\": \"javascript\"}"
    headers:
      Content-Type: "application/json"

- name: deploy map-reduce functions for population-db
  become: yes
  uri:
    url: http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_aurin_population }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"_id\": \"_design/population\",\
            \"views\": {\"allStates\": {\"map\": \"function (doc){emit(doc.State, doc.pop);}\"}},\
            \"language\": \"javascript\"}"
    headers:
      Content-Type: "application/json"