# Common vars
availability_zone: melbourne-qh2-uom
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb # Ubuntu 20.04
instance_key_name: group49
instance_flavor: uom.mse.2c9g
project_working_directory: /home/xuwang/CCC-COMP90024

# Security groups
security_groups:
  - name: ssh-security-group
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http-security-group
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  # - name: all-tcp-security-group
  #   description: "security group for any possible TCP connection"
  #   protocol: tcp
  #   port_range_min: 1
  #   port_range_max: 65535
  #   remote_ip_prefix: 0.0.0.0/0

# Volumes:
  - vol_name: instance_1_volume
    vol_size: 10
  - vol_name: instance_2_volume
    vol_size: 100
  - vol_name: instance_3_volume
    vol_size: 100
  - vol_name: instance_4_volume
    vol_size: 100

# Instance
instances:
  - name: instance_1
    volumes: ['instance_1_volume']
  - name: instance_2
    volumes: ['instance_2_volume']
  - name: instance_3
    volumes: ['instance_3_volume']
  - name: instance_4
    volumes: ['instance_4_volume']