---
- name: setup couchdb cluster | step 1.1
  become: yes
  uri:
    url: "http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_cluster_name }}"
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\", \"port\": \"5984\",\
             \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['dbServers'] | length }}\",\
             \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":{{ couchdb_password }}}"
    headers:
      Content-Type: "application/json"
    loop: "{{ groups['dbWorker'] }}"
# for node in ${othernodes} 
# do
#     curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup" \
#       --header "Content-Type: application/json"\
#       --data "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
#              \"username\": \"${user}\", \"password\":\"${pass}\", \"port\": \"5984\",\
#              \"remote_node\": \"${node}\", \"node_count\": \"$(echo ${nodes[@]} | wc -w)\",\
#              \"remote_current_user\":\"${user}\", \"remote_current_password\":\"${pass}\"}"
# done

- name: setup couchdb cluster | step 1.2
  become: yes
  uri:
    url: "http://{{ groups['dbMaster'][0] }}:5984/{{ couchdb_cluster_name }}"
    status_code: 201, 409
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
             \"port\": \"5984\", \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['dbServers'] | length }}\",\
             \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":{{ couchdb_password }}}"
    headers:
      Content-Type: "application/json"
    loop: "{{ groups['dbWorker'] }}"
# for node in ${othernodes}
# do
#     curl -XPOST "http://${user}:${pass}@${masternode}:5984/_cluster_setup"\
#       --header "Content-Type: application/json"\
#       --data "{\"action\": \"add_node\", \"host\":\"${node}\",\
#              \"port\": \"5984\", \"username\": \"${user}\", \"password\":\"${pass}\"}"
# done