---
# - name: Ensure .ssh directory exists.
#   file:
#     path: /home/ubuntu/.ssh
#     state: directory
#     mode: 0700
#     owner: ubuntu
#     group: ubuntu

- name: Add github ssh key
  copy:
    src: "inventory/githubKey.key"
    dest: /home/ubuntu/.ssh/githubKey
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Add ssh_config for github
  copy:
    src: "inventory/ssh_config"
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Create assignment folder
  file:
    path: '{{ remote_working_directory }}'
    state: directory

- name: Clone repo
  shell: git clone git@github.com:zachy-ho/cloud-assignment-2.git --config core.sshCommand="ssh -i /home/ubuntu/.ssh/githubKey"
  args:
    chdir: '{{ remote_working_directory }}'
