---
- name: Pull repo
  shell: git pull
  args:
    chdir: '{{ remote_git_directory }}'

- name: Generate aurin config file
  become: yes
  template:
    src: aurinSettings.py.j2
    dest: '{{ remote_working_directory }}/cloud-assignment-2/aurin/aurinSettings.py'

- name: Shutdown previous server
  become: yes
  shell: docker-compose down --rmi local
  args:
    chdir: '{{ remote_working_directory }}/cloud-assignment-2/aurin'

- name: Restart server
  become: yes
  shell: docker-compose up --build -d
  args:
    chdir: '{{ remote_working_directory }}/cloud-assignment-2/aurin'