- hosts: dbServers
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true

  roles:
    - deploy-couchdb

- hosts: dbMaster
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true

  roles:
    - deploy-cluster
    - deploy-git-pull
    # - deploy-crawler
