# # Setup and deploy CouchDB
# - hosts: dbServers
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true

#   roles:
#     - deploy-couchdb

# # Using curl (http requests) to form cluster
# - hosts: dbMaster
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true

#   roles:
#     - deploy-cluster

# # Deploy harvester on instance 2
# - hosts: dbMaster
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true

#   roles:
#     - deploy-harvester

# # Push aurin data to CouchDB on instance 3
# - hosts: backend
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true

#   roles:
#     - deploy-aurin

# # Deploy map-reduce functions
# - hosts: dbMaster
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true

#   roles:
#     - deploy-map-reduce

# Deploy frontend
- hosts: frontend
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true

  roles:
    - deploy-frontend