- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: instance-common
    - role: instance-images
    - role: instance-volumes
    - role: instance-security-groups
    - role: instance-creation