- hosts: localhost
  vars_files:
    - host_vars/instance_vars.yaml
  gather_facts: true

  roles:
    - role: instance-common
    - role: instance-images
    - role: instance-volumes
    - role: instance-security-groups
    - role: instance-creation