---
- name: Pull repo
  shell: git pull
  args:
    chdir: '{{ remote_git_directory }}'

- name: Generate harvester config file
  become: yes
  template:
    src: harvesterSettings.py.j2
    dest: '{{ remote_working_directory }}/cloud-assignment-2/harvester/harvesterSettings.py'

- name: Shutdown previous server
  become: yes
  shell: docker-compose down --rmi local
  args:
    chdir: '{{ remote_working_directory }}/cloud-assignment-2/harvester'

- name: Restart server
  become: yes
  shell: docker-compose up --build -d
  args:
    chdir: '{{ remote_working_directory }}/cloud-assignment-2/harvester'